name: build
on: push
    #paths: 
     # - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
        exclude:
          - os: macos-latest
            node: 10
    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Some
          MIDDLE_NAME: Cool
          LAST_NAME: Guy
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The previous step has finished successfully" 
      - name: my third step
        uses: action/checkout@v1
        with:
          node-version: 14
          registery-url: https://npm.pkg.github.com/
      
